### ISSUE TITLE
QT

### ISSUE THREAD

**Issue by Hietanne** [banksimul2022/group2#58]
content-type missing in HTTP POST, defaulting to application/x-www-form-urlencoded. Use QNetworkRequest::setHeader() to fix this problem.

antaa varoitukseksi postissa. 

Tein erillisen testi.exe mihin kokeilin pekka alaluukkaan HTTP post koodia. Antaa kyseisen virheilmoituksen.

En saanut myöskään integroitua kyseistä koodia DLL tiedostoon.

**Comment by EriKorh** [comment]
Selvitetty
