### ISSUE TITLE
RFID-kortinlukija

### ISSUE THREAD

**Issue by Hietanne** [banksimul2022/group2#67]
Ei saa tunnistettua com-porttia. Kun avasi notepadin ja laittoi RFID kortin lukijaan se söytti notepadiin tietoa kuitenkin.

**Comment by t33bu** [comment]
Tarkistettavas asia: sarjaportti ei voi olla auki kahdessa sovelluksessa yhtaikaa. Eli, jos se on jo notepadiss tmv auki niin sitä ei enää saa Qt-sovellukseen auki.

**Comment by Hietanne** [comment]
Aleksi kävi hakemassa uuden lukijan.
