### ISSUE TITLE
DLL Pincode

### ISSUE THREAD

**Issue by EriKorh** [banksimul2022/group2#74]
Ongelmia signaalien ja slottien kanssa.

**Comment by Hietanne** [comment]
![image](https://user-images.githubusercontent.com/94108317/163995249-1fc5a1b6-ab9d-4e3e-9d8d-e6d3e2221cc8.png)

**Comment by Hietanne** [comment]
Ongelma saatu korjattua. Connect toimii ylhäällä kuva connectista mikä tulee exe tiedostoon että saa pin koodin.

**Comment by Hietanne** [comment]
![image](https://user-images.githubusercontent.com/94108317/163995436-6b506a64-c738-4ea5-b5b4-2cba2cb89f7b.png)
Kuvassa slotti mihin signaali kiinnitetään. Mikä tulostaa oikean pin koodin.

**Comment by Hietanne** [comment]
EXE tiedostossa täytyy ensin luoda olio DLLPinCodesta ennekuin laittaa connectin.

**Comment by Hietanne** [comment]
![image](https://user-images.githubusercontent.com/94108317/163998737-4f6f78e2-6991-4f31-a899-a05ab95dfc40.png)
Toinen connecti täytyy laittaa exe tiedostoon johon lähetetään QString joka on true tai false. Ja jos on yli 3 yritystä lähetetään signaali cardlocked mikä ei palauta mitään. Ja sulkee dialogi ikkunan.

**Comment by Hietanne** [comment]
![image](https://user-images.githubusercontent.com/94108317/164001607-606632b8-c401-4dfc-a28d-ca4b5bb954f1.png)
Kuvassa näkyy miten aloitetaan DLLPinCode dialogi. Samalla sille täytyy antaa kortinnumero parametrinä.
